name: Github CI Unit Testing for Legacy Environments

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        python-version: [2.7, 3.5, 3.6]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # configure python
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install deps
      - name: Install dependencies for ${{ matrix.os }} Python ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install scipy

      # find and run all unit tests
      - name: Run unit tests
        run: python -m unittest discover test
